- editors/tiptap/src/vue/c-tiptap-link-edit.vue
* Adjusted styles for the editing links feature
https://jira.xwiki.org/browse/CRISTAL-204
* Add styles for editing links
On Shoelace
On Vuetify
-
* N/A
> CRISTAL-204: CSS for editing links

- editors/tiptap/src/vue/c-tiptap-link-suggest.vue
- editors/tiptap/src/vue/c-tiptap-selector.vue
- skin/src/vue/c-content.vue
* Created basic styles for the tables
https://jira.xwiki.org/browse/CRISTAL-203
* Creates the basic styles for tables inside documents
* For now, these styles are done with the ```:global``` tag because tables that come from the XWiki backend don't have any id, just basic HTML.
-
* N/A
> CRISTAL-203: Tables are missing CSS

- core/backends/backend-github/src/githubStorage.ts
- core/backends/backend-nextcloud/src/NextcloudWikiConfig.ts
- core/backends/backend-nextcloud/src/nextcloudStorage.ts
- core/backends/backend-xwiki/src/__tests__/xwikiStorage.test.ts
- core/backends/backend-xwiki/src/xwikiStorage.ts
- core/hierarchy/hierarchy-default/src/utils.ts
- core/hierarchy/hierarchy-nextcloud/package.json
- core/hierarchy/hierarchy-nextcloud/src/components/componentsInit.ts
- core/hierarchy/hierarchy-nextcloud/src/index.ts
- core/hierarchy/hierarchy-nextcloud/tsconfig.json
- core/hierarchy/hierarchy-nextcloud/vite.config.ts
- electron/renderer/package.json
- electron/renderer/src/index.ts
- electron/storage/src/components/fileSystemStorage.ts
- lib/src/components/DefaultCristalApp.ts
- pnpm-lock.yaml
- skin/src/vue/c-content.vue
- web/package.json
- web/src/index.ts
https://jira.xwiki.org/browse/CRISTAL-226
* Add a page hierarchy resolver for Nextcloud
* Factorize `FileSystemPageHierarchyResolver` and `NextcloudPageHierarchyResolver` through `getPageHierarchyFromPath()`
* Fix small issues with the Nextcloud backend
Considering the page ids with the Nextcloud backends are simple paths, we can reuse the same logic for the breadcrumb as for the FileSystem backend.
The breadcumb was tested manually with a local Nextcloud instance.
* N/A
> CRISTAL-226: Breadcrumb for Nextcloud

- core/navigation-tree/navigation-tree-filesystem/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-nextcloud/src/components/componentsInit.ts
https://jira.xwiki.org/browse/CRISTAL-239
Add a simple fallback when a node has an empty page name.
I reproduced the issue and tested the fix manually.
* N/A
> CRISTAL-239: Navigation tree present odd results with the Filesystem backend

- ds/shoelace/src/utils/navigation-tree-selection.ts
- ds/shoelace/src/vue/x-navigation-tree.vue
- ds/vuetify/src/vue/x-navigation-tree.vue
https://jira.xwiki.org/browse/CRISTAL-244
Vuetify's "activation" and Shoelace's "selection" are now fully handled manually to only have a single node selected: the current page (or clicked link if a clickAction is present).
Confusing hover effects have also been disabled.
~~In this PR, Vuetify's navigation tree was also made more compact to align a bit more with Shoelace's one.~~
Test suite was run fully.
* N/A
> CRISTAL-244: Clicking outside the text in the navigation tree nodes does nothing

- core/document/document-default/src/defaultDocumentService.ts
- core/model/model-reference/model-reference-xwiki/src/__tests__/defaultLocalURLSerializer.test.ts
- core/model/model-reference/model-reference-xwiki/src/xWikiModelReferenceSerializer.ts
- core/navigation-tree/navigation-tree-api/package.json
- core/navigation-tree/navigation-tree-api/src/index.ts
- core/navigation-tree/navigation-tree-filesystem/package.json
- core/navigation-tree/navigation-tree-filesystem/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-github/package.json
- core/navigation-tree/navigation-tree-github/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-nextcloud/package.json
- core/navigation-tree/navigation-tree-nextcloud/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-xwiki/package.json
- core/navigation-tree/navigation-tree-xwiki/src/components/componentsInit.ts
- ds/shoelace/src/vue/x-navigation-tree.vue
- ds/vuetify/package.json
- ds/vuetify/src/vue/x-navigation-tree.vue
- editors/tiptap/package.json
- editors/tiptap/src/vue/c-edit-tiptap.vue
- pnpm-lock.yaml
- skin/package.json
- skin/src/vue/c-page-creation-menu.vue
- sources/xwiki/mock-server/src/index.ts
- web/e2e/main-page.spec.ts
- web/e2e/pageObjects/Sidebar.ts
- web/playwright.config.ts
https://jira.xwiki.org/browse/CRISTAL-329
* This PR fixes an issue with realtime editor that was fetching the wrong page on creation.
* Page creation was also improved to use SpaceReferences instead of manually crafting the new reference.
* While reviewing this issue, I detected a few edge cases on the navigation tree I did not catch before. It should now be more reliable.
* This also adds a small UI test that checks realtime editor opens properly, with the right data, on page creation.
Fixing the issue with the realtime editor led to a new one: when the editor first saves a page that did not exist previously, the DocumentService is not updated with the currently edited page. This was not reproducible with the XWiki backend since the server always returns a document, even if the page …
> CRISTAL-329: Creating a nested page fails to add a page with the right name

- skin/src/vue/c-sidebar-panel.vue
https://jira.xwiki.org/browse/CRISTAL-324
* This PR fixes a small inconsistency of spacing between the buttons and tree navigation on the sidebar panel
* -
-
* N/A
> CRISTAL-324: Bad layout / margin for the create page button and navigation tree

- core/attachments/attachments-ui/src/vue/AttachmentsTab.vue
- core/attachments/attachments-ui/src/vue/AttachmentsTable.vue
- ds/shoelace/src/vue/css/style.css
- ds/vuetify/src/vue/css/style.css
- editors/tiptap/src/vue/c-edit-tiptap.vue
- skin/src/vue/c-content.vue
- skin/src/vue/c-view.vue
https://jira.xwiki.org/browse/CRISTAL-300
* Add basic styles for `<table>` elements
* Additional styles for the `<a>`element were necessary to provide a good table reading experience;
* Because of these additional elements, some colors were imported to the basic `style.css`on each design system.
**Table on document content**
**Attachments table**
-
* N/A
> CRISTAL-300: CSS for the table displayer

- core/hierarchy/hierarchy-xwiki/package.json
- core/hierarchy/hierarchy-xwiki/src/components/componentsInit.ts
- pnpm-lock.yaml
- skin/src/vue/c-content.vue
- sources/xwiki/mock-server/src/index.ts
- web/e2e/main-page.spec.ts
- web/e2e/pageObjects/Breadcrumb.ts
- web/e2e/pageObjects/NavigationTree.ts
https://jira.xwiki.org/browse/CRISTAL-364
The previous Breadcrumb implementation was using direct XWiki links, obtained from XWiki's API, and relied on a "click listener" set on the links. However, after the refactoring done for [CRISTAL-274](https://jira.xwiki.org/browse/CRISTAL-274), the listener seems to no longer work properly with Shoelace components (that use a lot of shadow DOMs). As such, this implementation drops the listener and makes proper local Cristal links instead, which should be more stable.
While using the ModelReference API for this PR, I noticed a few edge cases that were not properly handled (my test instance has a few documents with special characters, and they were not properly escaped). So I fixed them in both the parser and serializer, and also added a unit test …
> CRISTAL-364: Breadcrumb links not working with Shoelace

- core/navigation-tree/navigation-tree-filesystem/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-nextcloud/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-xwiki/src/components/componentsInit.ts
https://jira.xwiki.org/browse/CRISTAL-236
This PR adds some checks (with minimal performance hit) for FileSystem and Nextcloud to not display an expand button if a node has no child.
For XWiki, it adds filtering to the backend request through query parameters that I missed previously.
GitHub did not have this issue by design.
N/A
N/A
The whole test suite was run locally.
* N/A
> CRISTAL-236: Navigation tree with no child sometimes have an expand button

- core/attachments/attachments-ui/src/vue/AttachmentsTable.vue
* Fix for the alignment issue on Vuetify
https://jira.xwiki.org/browse/CRISTAL-409
* Fix the spacing issue that's occuring when using the Vuetify DS
-
Before:
After:
-
* N/A
> CRISTAL-409: No attachments message is badly aligned

- ds/vuetify/src/vue/x-alert.vue
- skin/langs/translation-en.json
* Fixes the color of links inside the message component of Vuetify
* Small correction on a message localization for EN language
https://jira.xwiki.org/browse/CRISTAL-414
* Fix for link colors inside the message component of Vuetify
* Also fixes a small translating issue in English
Before: 
After:
-
* N/A
> CRISTAL-414: Color and label issue for link in messages

- core/attachments/attachments-ui/src/vue/AttachmentsTable.vue
- Fix to the table margins
https://jira.xwiki.org/projects/CRISTAL/issues/CRISTAL-419
* This PR fizes the alignment error on the attachment table
* This is similar to CRISTAL-409, but I didn't notice until the previous PR created.
Before:
After:
-
* N/A
> CRISTAL-419: Attachments table is misaligned on Vuetify

- core/info-actions/info-actions-ui/src/vue/InfoAction.vue
- Padding and style adjusments to the info-actions buttons
https://jira.xwiki.org/projects/CRISTAL/issues/CRISTAL-420
* This PR bring the style of info-action to be more inline to buttons on both DS.
* As a future improvement, these components should probably be converted to proper buttons.
**Before:**
**After:**
-
* N/A
> CRISTAL-420: Info-actions and more options buttons have different sizes

- ds/shoelace/src/vue/form/x-file-input.vue
https://jira.xwiki.org/projects/CRISTAL/issues/CRISTAL-423
* On Shoelace, there's an alignment problem on the border of the uploadForm component. This PR fixes this small issue
* Shoelace does not have a custom component like Vuetify so both are a bit different handling this.
Before:
After:
-
* N/A
> CRISTAL-423: Odd alignment of the border on AttachmentUploadForm component

- editors/tiptap/src/extensions/link.ts
- skin/src/vue/c-article.vue
- skin/src/vue/c-view.vue
* Implemented an icon for the external links as it is in XWiki Standard
https://jira.xwiki.org/projects/CRISTAL/issues/CRISTAL-422
* Provides proper styles for the external link icon
* There was a style for external links before, but it was only an italic text that didn't provide much context.
* In this implementation we are using the Bootstrap icons pack,
Before:
After:
-
* N/A
> CRISTAL-422: Implement styles for external links

- ds/vuetify/src/vue/x-navigation-tree.vue
https://jira.xwiki.org/browse/CRISTAL-401
There was a race condition between the tree expansion on page change, and the node creation on documentChange events. Both could start as soon as the editor was closed and then pause while fetching the children nodes.
This is an issue only with the Vuetify implementation.
N/A
* N/A
> CRISTAL-401: It is possible to end up with duplicate entries in the document tree

- core/model/model-reference/model-reference-xwiki/src/xWikiModelReferenceHandler.ts
- skin/langs/translation-en.json
- skin/langs/translation-fr.json
- skin/src/vue/c-page-creation-menu.vue
- sources/xwiki/mock-server/src/index.ts
https://jira.xwiki.org/browse/CRISTAL-408
This adds an alert in the page creation dialog if the page already exists, with an action to edit it instead.
N/A
The UI tests were run locally.
* N/A
> CRISTAL-408: We don't check if a page already exists on page creation

- skin/src/vue/c-article.vue
- skin/src/vue/c-view.vue
* Added styles for code blocks
https://jira.xwiki.org/browse/CRISTAL-450
* Added affected styles
-
Before:
After:
-
* N/A
> CRISTAL-450: Code block are not styled

- skin/src/vue/c-article.vue
- skin/src/vue/c-view.vue
* Added styles for the blockquote element
https://jira.xwiki.org/browse/CRISTAL-449
* Added affected styles 
-
Before:
After:
-
* N/A
> CRISTAL-449: Blockquotes are not styled

- package.json
https://jira.xwiki.org/browse/CRISTAL-466
* Allow Electron to run its postinstall script when installed with PNPM 11
* Starting with version 11, PNPM doesn't run postinstall scripts by default anymore. Packages need to be manually whitelisted for their script to run.
N/A
N/A
* N/A
cc @manuelleduc
> CRISTAL-466: Whitelist Electron to run postinstall script with PNPM 11

- .vscode/extensions.json
N/A
* Remove deprecated TypeScript plugin for Vue from the list of recommanded VSCode extensions
N/A
N/A
N/A
* N/A
cc @manuelleduc
> [Misc] Remove deprecated Vue TypeScript VSCode extension

- electron/.electron-builder.config.js
- electron/package.json
https://jira.xwiki.org/browse/CRISTAL-467
* Add a Flatpak to the list of Linux build outputs
* Flatpak is useful for distributing under Linux, as it contains all required dependencies and also enables sandboxing
* AppImage currently [don't work properly with Ubuntu 22.04](https://github.com/electron/electron/issues/17972). Flatpak can be an alternative for users who still want to download a standalone file and get sandboxing
N/A
N/A
* N/A
cc @manuelleduc
> CRISTAL-467: Add Flatpak image

- core/navigation-tree/navigation-tree-api/src/index.ts
- core/navigation-tree/navigation-tree-default/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-filesystem/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-github/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-nextcloud/src/components/componentsInit.ts
- core/navigation-tree/navigation-tree-xwiki/src/components/componentsInit.ts
- ds/api/src/XNavigationTree.ts
- ds/api/src/XNavigationTreeSelect.ts
- ds/api/src/index.ts
- ds/shoelace/src/vue/form/x-navigation-tree-select.vue
- ds/shoelace/src/vue/x-navigation-tree-item.vue
- ds/shoelace/src/vue/x-navigation-tree.vue
- ds/vuetify/src/vue/form/x-navigation-tree-select.vue
- ds/vuetify/src/vue/x-navigation-tree.vue
- skin/src/vue/c-sidebar.vue
https://jira.xwiki.org/browse/CRISTAL-430
This changes a few APIs to include or not terminal pages in navigation trees.
N/A
N/A
Everything was tested manually.
* N/A
> CRISTAL-430: XWiki terminal pages are not excluded on the page creation form

- core/browser/browser-api/src/index.ts
- core/browser/browser-default/src/components/browser-api-default.ts
- electron/browser/package.json
- electron/browser/src/components/browser-api-electron.ts
- electron/browser/src/electron/main/index.ts
- electron/browser/src/electron/preload/index.ts
- electron/state/package.json
- electron/state/src/index.ts
- electron/state/tsconfig.json
- electron/state/tsdoc.json
- electron/state/vite.config.js
- electron/storage/package.json
- electron/storage/src/components/FileSystemConfig.ts
- electron/storage/src/electron/main/index.ts
- electron/storage/src/electron/preload/apiTypes.ts
- electron/storage/src/electron/preload/index.ts
- lib/src/components/DefaultCristalApp.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
https://jira.xwiki.org/browse/CRISTAL-496
This PR adds support for the `storageRoot` configuration key to the FileSystem backend.
The `storageRoot` value needs to be made available to the main process of electron. In order to do this, a state package was created at `electron/state` to set and get this information.
BrowserApi and its Electron implementation were slightly refactored to handle that.
N/A
The test suite was run locally.
* N/A
> CRISTAL-496: Allow the file system backend root location to be configurable

- editors/blocknote-headless/src/vue/c-blocknote-view.vue
N/A
* Restored missing toolbar on most block types in BlockNote editor
* An error is shown when a custom toolbar is missing for a particular block type. But, as we did not implement a custom toolbar for all elements yet, this error is shown for most block types such as tables, lists, block quotes, code blocks, some headings, etc.
N/A
N/A
* N/A
> Fix: missing toolbar for most block types in BlockNote

- ds/vuetify/src/vue/css/style.css
* Added a Vuetify specific CSS rule to make the vertical scrollbar auto
https://jira.xwiki.org/browse/CRISTAL-535
* Just a simple rule to get rid of the extra space on Vuetify
* 
Kind of hard to see, but the space on the right side of the Viewport is gone.
**Before:**
**After:**
-
* N/A
> CRISTAL-535: Double scrollbars on Vuetify

- api/src/api/cristalApp.ts
- core/backends/backend-github/src/githubStorage.ts
- core/backends/backend-nextcloud/src/nextcloudStorage.ts
- core/backends/backend-xwiki/src/xwikiStorage.ts
- core/document/document-api/src/index.ts
- core/document/document-default/src/defaultDocumentService.ts
- core/page-actions/page-actions-ui/src/vue/MovePage.vue
- editors/blocknote/src/vue/c-edit-blocknote.vue
- editors/tiptap/src/vue/c-edit-tiptap.vue
- electron/storage/src/components/fileSystemStorage.ts
- electron/storage/src/electron/preload/apiTypes.ts
- electron/storage/src/electron/preload/index.ts
- lib/src/components/DefaultCristalApp.ts
- sharedworker/impl/src/components/defaultQueueWorker.ts
- sharedworker/impl/src/components/workerCristalApp.ts
- skin/src/vue/c-document-refresher.vue
- skin/src/vue/c-edit.vue
- skin/src/vue/c-page-creation-menu.vue
https://jira.xwiki.org/browse/CRISTAL-514
* Enables creating pages with the BlockNote editor
This PR is very heavy as it contains a lot of changes necessary for proper page creation instead of just "bruteforcing". The current (previous) way of creating pages (with TipTap) is as follows!
1. When the new page name is submitted, the page is not actually created
2. The router navigates to the edit page and loads TipTap
3. TipTap sees the page is not defined, and creates it with an empty content
This is not only less than ideal as it makes the editor more complex (as it needs to handle non-existent documents) but also requires to duplicate this specific logic across all editor components.
This PR changes that ; the page is now created from within the modal, and _only after_ is the editor …
> CRISTAL-514: Enable creating pages with BlockNote

- editors/blocknote-headless/src/vue/c-blocknote-view.vue
https://jira.xwiki.org/browse/CRISTAL-516
* Make BlockNote look more like rendered pages
A lot of things to say on this one!
* I tried different approaches, and ended up with the simplest route: using CSS to override style inside the BlockNote's HTML editor elements
* All style elements (font names, sizes, paddings, margins, etc.) use variables imported from the current Design System. This means BlockNote's inner style will now adapt to the selected DS.
* Bullet lists' markers cannot be made the same size as the rendered pages because they are unaligned HTML elements, so increasing their size leads to this:
* Lists of tasks are not consistent with the rendered pages as this would be too complex to do. But given they are not supported in XWiki's rendered pages, no one should theorically …
> CRISTAL-516: BlockNote is not WYSIWYG

- core/backends/backend-xwiki/src/xwikiStorage.ts
- sources/xwiki/mock-server/src/index.ts
https://jira.xwiki.org/browse/CRISTAL-504
Small changes to use the endpoints provided by https://github.com/xwiki-contrib/cristal-integration.
**Warning:** do not merge until https://github.com/xwiki-contrib/cristal-integration/pull/1/ is merged.
* N/A
N/A
N/A
* N/A
> CRISTAL-504: Migrate the groovy extension for XWiki into a contrib extension in Java

- core/fn-utils/src/index.ts
- editors/blocknote-headless/src/uniast/bn-to-uniast.ts
- editors/blocknote-react/src/blocknote/index.ts
https://jira.xwiki.org/browse/CRISTAL-573
* Remove support for togglable list items in BlockNote
* Fix togglable headings' content preventing save
* We don't have support for togglable list items currently, so just like files and audio items, we remove them from the schema for now
* Headings previously couldn't have children elements, so saving doesn't work anymore - this PR fixes that and saves the child as being normal elements below their parent heading
N/A
N/A
* N/A
> CRISTAL-573: Upgrade to blocknote 0.33.0

- core/fn-utils/src/index.ts
- core/uniast/src/__tests__/converters.test.ts
- core/uniast/src/ast.ts
- core/uniast/src/markdown/md-to-uniast.ts
- core/uniast/src/markdown/uniast-to-md.ts
- editors/blocknote-headless/src/index.ts
- editors/blocknote-headless/src/uniast/bn-to-uniast.ts
- editors/blocknote-headless/src/uniast/uniast-to-bn.ts
- editors/blocknote-react/src/blocknote/index.ts
- editors/blocknote-react/src/blocknote/macros/XWikiMacroHtmlBlock.tsx
- editors/blocknote-react/src/blocknote/macros/XWikiMacroInlineHtml.tsx
- editors/blocknote-react/src/blocknote/utils.ts
- editors/blocknote-react/src/components/BlockNoteViewWrapper.tsx
- editors/blocknote-react/src/index.tsx
- editors/blocknote/src/vue/c-edit-blocknote.vue
https://jira.xwiki.org/browse/CRISTAL-44
* Add support for client-side-rendered macros
* Macros can only be written inside React.js
* They are shown in the slash menu in BlockNote
* A set of default macros are provided by default, but they are not enabled automatically - the integration part needs to explicitly allow them. This allows disabling macros altogether easier.
* The integration part can provide additional macros if required
* Macros are setup during editor initialization, and cannot be changed afterwards
* Macros appear properly in UniAst and are supported in the Markdown converter
* A handful of tests have been added to ensure macros are parsed properly, even using slightly ambiguous syntax
* The parser for XWiki-specific syntax (internal links, internal images, macros) have …
> CRISTAL-44:  Macros can be viewed using client side rendering

- editors/blocknote-react/src/components/images/ImageFilePanel.tsx
- editors/blocknote-react/src/components/images/ImageSelector.tsx
https://jira.xwiki.org/browse/CRISTAL-616
* When editing an image in the editor, pre-fill the search field with the image's entity name (or current URL)
N/A
N/A
N/A
* N/A
> CRISTAL-616: pre-fill image selector popover with current URL / entity name
